# Generated by Django 3.2.7 on 2021-09-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_polygon_polygonarea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polygonarea",
            name="price",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
    ]
