# Generated by Django 3.2.7 on 2021-09-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="currency",
            field=models.CharField(max_length=245),
        ),
        migrations.AlterField(
            model_name="provider",
            name="language",
            field=models.CharField(
                choices=[
                    ("ENG", "English"),
                    ("SPA", "Spanish"),
                    ("CHI", "Chinese"),
                    ("FRA", "French"),
                    ("GER", "German"),
                    ("HIN", "Hindi"),
                    ("JPN", "Japanese"),
                    ("AR", "Arabic"),
                ],
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="Polygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("geojson_info", models.TextField()),
                (
                    "provider_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.provider"
                    ),
                ),
            ],
        ),
    ]
