# Generated by Django 3.2.7 on 2021-09-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210913_1019"),
    ]

    operations = [
        migrations.RenameField(
            model_name="polygon",
            old_name="geojson_info",
            new_name="geojson",
        ),
        migrations.AlterField(
            model_name="provider",
            name="currency",
            field=models.CharField(
                choices=[
                    ("INR", "India Ruppee"),
                    ("USD", "US Dollar"),
                    ("YEN", "Japanese Yes"),
                    ("EUR", "Euro"),
                    ("GBP", "Pound"),
                ],
                max_length=3,
            ),
        ),
    ]
